
 pr:
  - main
  - test2

 pool:
   vmImage: 'ubuntu-latest'

 steps:
 - task: SonarQubePrepare@5
   inputs:
    SonarQube: 'sonar_service'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=javapipeline-YMAL

 - task: JavaToolInstaller@0
   inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

 - task: Maven@4
   inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
 
 - task: SonarQubePublish@5
   inputs:
     pollingTimeoutSec: '300'

  